spring.application.name=demo

# --- CONFIGURAÇÕES DO BANCO DE DADOS (SEGURAS) ---
# O Spring vai buscar as variáveis no Docker ou no Servidor.
# O que vem depois dos ":" é um valor falso só para testes locais na sua máquina.

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bot_db}
spring.datasource.username=${DB_USER:admin_local}
spring.datasource.password=${DB_PASS:senha_local_123}

# --- CONFIGURAÇÕES DO HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect