spring.application.name=demo
google.calendar.id=799522abc4bd3e25d3e8392fa2c62f7a6890acd328510bf53f26b64cd2a05cb1@group.calendar.google.com


spring.datasource.url=jdbc:postgresql://localhost:5432/bot_db
spring.datasource.username=admin
spring.datasource.password=senha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect